### ISSUE TITLE
Black background makes edge labels unreadable

### ISSUE THREAD

**Issue by fgm** [hedwigz/entviz#11]
This is an issue similar to #8  with edge labels on the black background being basically unreadable, while they are just fine on a white background:

![Screenshot 2022-03-22 at 09 19 34](https://user-images.githubusercontent.com/143311/159437545-b0982136-40eb-4731-80b0-ee71428990cd.png)
![Screenshot 2022-03-22 at 09 19 56](https://user-images.githubusercontent.com/143311/159437549-2ee57d09-bf35-4975-81ad-26d872822002.png)

**Comment by hedwigz** [comment]
Hey @fgm !  
Thanks for reporting this.  
Would you like to contribute a PR? it should be fairly simple!
