### ISSUE TITLE
Colors of some of the nodes make them impossible to view

### ISSUE THREAD

**Issue by naormatania** [hedwigz/entviz#8]
Two examples that were output to me:

<img width="265" alt="Screen Shot 2021-10-24 at 7 53 22" src="https://user-images.githubusercontent.com/6978437/138581459-f0f43319-a179-4203-aa28-700797241fcc.png">
<img width="212" alt="Screen Shot 2021-10-24 at 7 53 53" src="https://user-images.githubusercontent.com/6978437/138581470-12d3f640-3c2b-4934-8664-9e70108fdd70.png">

It would be great if all nodes will be printed with only "light" colors (and also with no gray colors)
This change would make it possible to read the nodes names

**Comment by hedwigz** [comment]
Hey, @naormatania thanks for your feedback!  
Would you like to contribute a PR?  
I was thinking maybe using the following: https://www.npmjs.com/package/randomcolor

**Comment by hedwigz** [comment]
fixed https://github.com/hedwigz/entviz/pull/9
